### ISSUE TITLE
项目启动失败

### ISSUE THREAD

**Issue by BlankKelly** [leelance/spring-boot-all#2]
`ERROR StatusLogger appender Console has no parameter that matches element ThresholdFilter
21:18:58.525 [main] DEBUG org.springframework.boot.logging.ClasspathLoggingApplicationListener   - Application started with classpath: [file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/charsets.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/deploy.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/dnsns.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/localedata.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/sunec.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/zipfs.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/htmlconverter.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/javaws.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/jce.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/jfr.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/jfxrt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/jsse.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/management-agent.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/plugin.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/resources.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/rt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/ant-javafx.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/dt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/javafx-doclet.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/javafx-mx.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/jconsole.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/sa-jdi.jar, file:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/tools.jar, file:/Users/huitailang/IdeaProjects/spring-boot-all/spring-boot-hello/target/classes/, file:/Users/huitailang/.m2/repository/org/springframework/boot/spring-boot-starter/1.4.1.RELEASE/spring-boot-starter-1.4.1.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/springframework/boot/spring-boot/1.4.1.RELEASE/spring-boot-1.4.1.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/springframework/spring-context/4.3.3.RELEASE/spring-context-4.3.3.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.4.1.RELEASE/spring-boot-autoconfigure-1.4.1.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/springframework/spring-core/4.3.3.RELEASE/spring-core-4.3.3.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar, file:/Users/huitailang/.m2/repository/org/springframework/boot/spring-boot-starter-web/1.4.1.RELEASE/spring-boot-starter-web-1.4.1.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/hibernate/hibernate-validator/5.2.4.Final/hibernate-validator-5.2.4.Final.jar, file:/Users/huitailang/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar, file:/Users/huitailang/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar, file:/Users/huitailang/.m2/repository/com/fasterxml/classmate/1.3.1/classmate-1.3.1.jar, file:/Users/huitailang/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.3/jackson-databind-2.8.3.jar, file:/Users/huitailang/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.3/jackson-annotations-2.8.3.jar, file:/Users/huitailang/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.3/jackson-core-2.8.3.jar, file:/Users/huitailang/.m2/repository/org/springframework/spring-web/4.3.3.RELEASE/spring-web-4.3.3.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/springframework/spring-aop/4.3.3.RELEASE/spring-aop-4.3.3.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/springframework/spring-webmvc/4.3.3.RELEASE/spring-webmvc-4.3.3.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/springframework/spring-expression/4.3.3.RELEASE/spring-expression-4.3.3.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/springframework/data/spring-data-commons/1.12.3.RELEASE/spring-data-commons-1.12.3.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/springframework/spring-beans/4.3.3.RELEASE/spring-beans-4.3.3.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar, file:/Users/huitailang/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.21/jcl-over-slf4j-1.7.21.jar, file:/Users/huitailang/.m2/repository/org/springframework/boot/spring-boot-starter-log4j2/1.4.1.RELEASE/spring-boot-starter-log4j2-1.4.1.RELEASE.jar, file:/Users/huitailang/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.6.2/log4j-slf4j-impl-2.6.2.jar, file:/Users/huitailang/.m2/repository/org/apache/logging/log4j/log4j-api/2.6.2/log4j-api-2.6.2.jar, file:/Users/huitailang/.m2/repository/org/apache/logging/log4j/log4j-core/2.6.2/log4j-core-2.6.2.jar, file:/Users/huitailang/.m2/repository/org/slf4j/jul-to-slf4j/1.7.21/jul-to-slf4j-1.7.21.jar, file:/Users/huitailang/.m2/repository/com/lmax/disruptor/3.3.4/disruptor-3.3.4.jar, file:/Users/huitailang/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar, file:/Applications/IntelliJ%20IDEA.app/Contents/lib/idea_rt.jar]
21:18:58.530 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver   - Could not find key 'context.listener.classes' in any property source
21:18:58.533 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver   - Could not find key 'banner.image.location' in any property source
21:18:58.535 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver   - Could not find key 'banner.location' in any property source
`

**Comment by leehaut** [comment]
你是启动那个子项目? 你这log是没有错误展示的吧 ，你这个是log打印的debug信息 不影响运行的

**Comment by BlankKelly** [comment]
所有的项目都是这样，项目打印完日志直接就JVM进程直接就正常结束了:(
`20:41:58.173 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver   - Could not find key 'spring.liveBeansView.mbeanDomain' in any property source
20:41:58.194 [main] INFO  com.lance.hello.Application   - Started Application in 2.928 seconds (JVM running for 4.701)
20:41:58.206 [Thread-1] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext   - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6c256540: startup date [Wed Jan 04 20:41:56 CST 2017]; root of context hierarchy
20:41:58.207 [Thread-1] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory   - Returning cached instance of singleton bean 'lifecycleProcessor'
20:41:58.207 [Thread-1] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory   - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@54a07bc2: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,application,org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor,org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor,indexController,org.springframework.boot.autoconfigure.AutoConfigurationPackages,org.springframework.boot.autoconfigure.PropertyPlaceholderAutoConfiguration,org.springframework.boot.autoconfigure.condition.BeanTypeRegistry,propertySourcesPlaceholderConfigurer,org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$Jackson2ObjectMapperBuilderCustomizerConfiguration,standardJacksonObjectMapperBuilderCustomizer,spring.jackson-org.springframework.boot.autoconfigure.jackson.JacksonProperties,org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor,org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.store,org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperBuilderConfiguration,jacksonObjectMapperBuilder,org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperConfiguration,jacksonObjectMapper,org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration,jsonComponentModule,org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration,mbeanExporter,objectNamingStrategy,mbeanServer,org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration,org.springframework.boot.autoconfigure.web.HttpMessageConvertersAutoConfiguration$StringHttpMessageConverterConfiguration,stringHttpMessageConverter,spring.http.encoding-org.springframework.boot.autoconfigure.web.HttpEncodingProperties,org.springframework.boot.autoconfigure.web.JacksonHttpMessageConvertersConfiguration$MappingJackson2HttpMessageConverterConfiguration,mappingJackson2HttpMessageConverter,org.springframework.boot.autoconfigure.web.JacksonHttpMessageConvertersConfiguration,org.springframework.boot.autoconfigure.web.HttpMessageConvertersAutoConfiguration,messageConverters,org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration,spring.info-org.springframework.boot.autoconfigure.info.ProjectInfoProperties,org.springframework.boot.autoconfigure.web.WebClientAutoConfiguration$RestTemplateConfiguration,restTemplateBuilder,org.springframework.boot.autoconfigure.web.WebClientAutoConfiguration]; root of factory hierarchy
20:41:58.207 [Thread-1] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter   - Unregistering JMX-exposed beans on shutdown

Process finished with exit code 0`

**Comment by leehaut** [comment]
@BlankKelly   我刚刚测试了spring-boot-shiro demo，运行在jdk8下 没有发现启动错误， 你检查下你的jdk版本，然后编译下项目 看看是否有错误出现

**Comment by Jay20160803** [comment]
@BlankKelly 运行shiro项目报错
18:49:30.236 [main] ERROR org.springframework.boot.SpringApplication   - Application startup failed org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at com.lance.shiro.SimpleApplication.main(SimpleApplication.java:12) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) ~[idea_rt.jar:?]
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:189) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	... 13 more

**Comment by zhanghaichaogit** [comment]
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<version>1.5.1.RELEASE</version>
		</dependency>
需要在子项目引用

**Comment by Subfire** [comment]
我也是启动失败：

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.1.RELEASE)

13:25:42.353 [main] INFO  com.lance.easyui.SimpleApplication   - Starting SimpleApplication on Subfire-PC with PID 7612 (D:\workspace\spring-boot-all\spring-boot-easyui-kindeditor\target\classes started by Administrator in D:\workspace\spring-boot-all\spring-boot-parent)
13:25:42.356 [main] INFO  com.lance.easyui.SimpleApplication   - No active profile set, falling back to default profiles: default
13:25:42.422 [background-preinit] INFO  org.hibernate.validator.internal.util.Version   - HV000001: Hibernate Validator 5.2.4.Final
13:25:42.534 [main] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext   - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7ac296f6: startup date [Fri Apr 07 13:25:42 CST 2017]; root of context hierarchy
13:25:45.724 [main] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter   - Registering beans for JMX exposure on startup
13:25:45.763 [main] INFO  com.lance.easyui.SimpleApplication   - Started SimpleApplication in 4.862 seconds (JVM running for 7.242)
13:25:45.767 [Thread-1] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext   - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7ac296f6: startup date [Fri Apr 07 13:25:42 CST 2017]; root of context hierarchy
13:25:45.769 [Thread-1] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter   - Unregistering JMX-exposed beans on shutdown

Process finished with exit code 0

Idea+JDK8，这每一个子项目都是怎么启动的啊？

**Comment by leehaut** [comment]
@Subfire  你先把spring-boot-parent 编译下 然后在编译下你要启动的项目

**Comment by Subfire** [comment]
@leelance 你这个项目在Idea中 用内置的Tomcat，修改jsp文件后不用重启 网页上刷新就能看到效果，建了个项目试了下却不行，您这个是要配置什么吗 怎么实现的啊？ 网上搜的都是要配外置Tomcat

**Comment by leehaut** [comment]
我是spring-boot用的内置tomcat插件
`

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-jasper</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
		</dependency>
`

[https://github.com/leelance/spring-boot-all/blob/master/spring-boot-parent/pom.xml](url)
